### ISSUE TITLE
Update webhook code to account for deprecated webhook.Validator API change

### ISSUE THREAD

**Issue by cwilkers** [sakhoury/siteconfig#29]
Per [kubernetes-sigs/kubebuilder#3721](https://github.com/kubernetes-sigs/kubebuilder/issues/3721), the webhook.Validator interface was deprecated, and has been removed in recent release of the API.

This causes compilation errors after bumping Go to 1.24 and  refreshing the vendor tree.

```
# github.com/openshift/assisted-service/api/v1beta1
vendor/github.com/openshift/assisted-service/api/v1beta1/agent_webhook.go:43:15: undefined: webhook.Validator
vendor/github.com/openshift/assisted-service/api/v1beta1/agentclassification_webhook.go:50:15: undefined: webhook.Validator
vendor/github.com/openshift/assisted-service/api/v1beta1/infraenv_webhook.go:41:15: undefined: webhook.Validator
FAIL	github.com/stolostron/siteconfig/api/v1alpha1 [build failed]
FAIL	github.com/stolostron/siteconfig/cmd [build failed]
FAIL	github.com/stolostron/siteconfig/internal/controller [build failed]
FAIL	github.com/stolostron/siteconfig/internal/controller/clusterinstance [build failed]
FAIL	github.com/stolostron/siteconfig/internal/controller/conditions [build failed]
```

Updating away from the webhook.Validator pattern is required to unblock https://github.com/stolostron/siteconfig/pull/353
